apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ack-resources
  title: AWS ACK Resources Template
spec:
  type: service
  owner: platform-team
  parameters:
    - title: S3 Configuration
      required: ['bucketName']
      properties:
        bucketName:
          title: Bucket Name
          type: string
  steps:
    - id: log
      name: Log
      action: debug:log
      input:
        message: Creating bucket ${{ parameters.bucketName }}
    
    - id: create-manifest
      name: Create S3 Bucket Manifest
      action: fetch:template
      input:
        url: github:richfrancoisjr/backstage-s3-template/manifests
        targetPath: ./
        values:
          bucketName: ${{ parameters.bucketName }}

    - id: apply-manifest
      name: Apply S3 Bucket Manifest
      action: kubernetes:apply
      input:
        path: s3-bucket.yaml
