apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ack-resources
  title: AWS ACK Resources Template
  description: Template to create AWS S3 buckets using ACK controller
spec:
  type: service
  owner: platform-team
  parameters:
    - title: S3 Configuration
      required: ['bucketName']
      properties:
        bucketName:
          title: Bucket Name
          type: string
          description: Name of the S3 bucket to create
          pattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
  
  steps:
    - id: log
      name: Log
      action: debug:log
      input:
        message: Creating bucket ${{ parameters.bucketName }}
    
    - id: create-s3-manifest
      name: Create S3 Bucket Manifest
      action: fs:write
      input:
        path: s3-bucket.yaml
        content: |
          apiVersion: s3.services.k8s.aws/v1alpha1
          kind: Bucket
          metadata:
            name: ${{ parameters.bucketName }}
            namespace: default
          spec:
            name: ${{ parameters.bucketName }}
            publicAccessBlock:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            versioning:
              status: Enabled

    - id: apply-manifest
      name: Apply S3 Bucket Manifest
      action: kubernetes:apply
      input:
        path: s3-bucket.yaml

  output:
    links:
      - title: S3 Bucket
        url: https://s3.console.aws.amazon.com/s3/buckets/${{ parameters.bucketName }}
