apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ack-resources
  title: AWS ACK Resources Template
spec:
  type: service
  owner: platform-team
  parameters:
    - title: S3 Configuration
      required: ['bucketName']
      properties:
        bucketName:
          title: Bucket Name
          type: string
  steps:
    - id: log
      name: Log
      action: debug:log
      input:
        message: Creating bucket ${{ parameters.bucketName }}
    
    - id: create-manifest
      name: Create S3 Bucket Manifest
      action: fetch:template
      input:
        targetPath: ./
        values:
          bucketName: ${{ parameters.bucketName }}
        template: |
          apiVersion: s3.services.k8s.aws/v1alpha1
          kind: Bucket
          metadata:
            name: ${{ values.bucketName }}
            namespace: default
          spec:
            name: ${{ values.bucketName }}
            publicAccessBlock:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            versioning:
              status: Enabled

    - id: apply-manifest
      name: Apply S3 Bucket Manifest
      action: kubernetes:apply
      input:
        path: s3-bucket.yaml
