apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ack-resources
  title: AWS ACK Resources Template
spec:
  type: service
  owner: platform-team
  parameters:
    - title: S3 Configuration
      required: ['bucketName']
      properties:
        bucketName:
          title: Bucket Name
          type: string
  steps:
    - id: log
      name: Log
      action: debug:log
      input:
        message: Creating bucket ${{ parameters.bucketName }}
    
    - id: create-manifest
      name: Create S3 Bucket Manifest
      action: fetch:template
      input:
        url: ./manifests/  # Changed from absolute URL to relative path
        targetPath: ./
        values:
          bucketName: ${{ parameters.bucketName }}

    - id: show-manifest
      name: Show Generated Manifest
      action: debug:log
      input:
        message: |
          S3 bucket manifest created successfully!
          
          To apply this manifest to your cluster, run:
          kubectl apply -f s3-bucket.yaml
          
          The manifest file has been generated with bucket name: ${{ parameters.bucketName }}

