apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ack-resources
  title: AWS ACK Resources Template
  description: Deploy S3 bucket using AWS Controllers for Kubernetes
  tags:
    - aws
    - s3
    - ack
    - kubernetes
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Application Information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name for your application
          pattern: '^[a-z0-9-]+$'
        owner:
          title: Owner
          type: string
          description: Owner of the application
          default: platform-team
    - title: AWS Resources Configuration
      required:
        - bucketName
      properties:
        bucketName:
          title: S3 Bucket Name
          type: string
          description: Name for the S3 bucket (must be globally unique)
          pattern: '^[a-z0-9.-]+$'
  steps:
    - id: create-s3-bucket
      name: Create S3 Bucket
      action: kubernetes:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: s3.services.k8s.aws/v1alpha1
          kind: Bucket
          metadata:
            name: ${{ parameters.name }}-s3-bucket
            namespace: default
          spec:
            name: ${{ parameters.bucketName }}
            publicAccessBlock:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            versioning:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
              - applyServerSideEncryptionByDefault:
                  sseAlgorithm: AES256
